# Install and start SabNZB Docker Image

- name: Build and Start docker Image
  docker_container:
    image: "linuxserver/sabnzbd"
    name: "sab"
    env:
      PUID: '{{ sab_user_id }}'
      PGID: '{{ sab_group_id }}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '{{ sab_directory }}:/config'
      - '{{ host_media_downloaded }}:/downloads'
      - '{{ host_media_downloading }}:/incomplete-downloads'
    ports: '8080:8080'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "SabNZB" 
