# Install and start SabNZB Docker Image

- name: Build and Start docker Image
  docker:
    image: "linuxserver/sabnzbd"
    name: "sab"
      PUID: '{{ sab_user_id }}'
      PGID: '{{ sab_group_id }}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '{{ sab_directory }}/config:/config'
      - '{{ sab_directory }}/downloads:/downloads'
      - '{{ sab_directory }}/incomplete-downloads:/incomplete-downloads'
    ports: '8080:8080'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "SabNZB" 
