# Install and start SabNZB Docker Image

- name: Build and Start docker Image
  docker_container:
    image: "linuxserver/sabnzbd"
    name: "sab"
    env:
      PUID: '{{ user_id }}'
      PGID: '{{ group_id }}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '{{ sab_directory }}:/config'
      - '{{ host_media }}:/downloads'
      - '{{ host_media_downloading }}:/incomplete-downloads'
    ports: '{{ sab_port }}:{{ sab_port }}'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "SabNZB" 
