- name: 'Start the radarr docker container'
  docker_container:
    image: "linuxserver/radarr"
    name: "radarr"
    env:
      PUID: '{{ radarr_user_id }}'
      PGID: '{{ radarr_group_id }}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '{{ radarr_directory }}:/config'
      - '{{ host_media_downloaded }}:/downloads'
      - '{{ host_media_movies_path }}:/movies'
    ports: '7878:7878'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "radarr"
