- name: 'Start the Organizr docker container'
  docker_container:
    image: "lsiocommunity/organizr:latest"
    name: "organizr"
    env:
      PUID: '{{ user_id }}'
      PGID: '{{ group_id }}'
    volumes:
      - '{{ organ_directory }}:/config'
    ports: '{{ organ_port }}:80'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "organizr"
