- name: 'Start the Organizr docker container'
  docker_container:
    image: "lsiocommunity/organizr"
    name: "organizr"
    env:
      PUID: '{{ organ_user_id }}'
      PGID: '{{ organ_group_id }}'
    volumes:
      - '{{ organ_directory }}:/config'
    ports: '8181:80'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "organizr"
