# This play book handles the downloading of necessary packages and applies firewall opening on the server.

- name: Install necessary packages
  yum: name={{item}} state=installed
  with_items:
    - git
    - curl
    - wget
    - yum-utils

- name: Add Docker GPG key
  rpm_key:
    state: present
    key: https://yum.dockerproject.org/gpg

- name: Add repository
  yum_repository:
    name: docker
    description: Docker Centos Repo
    baseurl: https://yum.dockerproject.org/repo/main/centos/7 

- name: Install docker
  yum: name=docker-engine state=latest update_cache=yes

- name: Start and Enable the docker service
  service: name=docker state=started enabled=yes
 
- name: test to see if selinux is running and shut it off.
  command: getenforce
  register: sestatus
  changed_when: false

- name: Open up plex port
  firewalld: port={{ plex_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sab port
  firewalld: port={{ sab_port1 }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sab port
  firewalld: port={{ sab_port2 }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for couch potato port
  firewalld: port={{ couch_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sonarr port
  firewalld: port={{ sonarr_port }}/tcp permanent=true state=enabled immediate=yes

- name: Open up plex port
  firewalld: port={{ plex_port }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sab port
  firewalld: port={{ sab_port1 }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sab port
  firewalld: port={{ sab_port2 }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for couch potato port
  firewalld: port={{ couch_port }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sonarr port
  firewalld: port={{ sonarr_port }}/udp permanent=true state=enabled immediate=yes
