# This play book handles the downloading of necessary packages and applies firewall opening on the server.

- name: Install necessary packages
  yum: name={{item}} state=installed
  with_items:
    - git
    - curl
    - wget
    - yum-utils
    - python-pip

- name: Install docker
  pip: name={{item}}
  with_items:
    - docker
    - docker-py

- name: Start and Enable the docker service
  service: 
    name: docker 
    state: started 
    enabled: yes

# TODO: Don't do this.

- name: test to see if selinux is running and shut it off.
  command: getenforce
  register: sestatus
  changed_when: false

# TODO: Seriously, don't do that.

# Open up ports for all those dope applications.

- name: Open up the TCP ports
  firewalld: 
    port: "{{ item }}/tcp" 
    permanent: true 
    state: enabled 
    immediate: yes
  with_items:
    - "{{ plex_port }}"
    - "{{ sab_port }}"
    - "{{ radarr_port }}"
    - "{{ sonarr_port }}"
    - "{{ hydra_port }}"
    - "{{ ombi_port }}"
    - "{{ organ_port }}"

- name: Open up the TCP ports
  firewalld:
    port: "{{ item }}/udp" 
    permanent: true 
    state: enabled 
    immediate: yes
  with_items:
    - "{{ plex_port }}"
    - "{{ sab_port }}"
    - "{{ radarr_port }}"
    - "{{ sonarr_port }}"
    - "{{ hydra_port }}"
    - "{{ ombi_port }}"
    - "{{ organ_port }}"

