# This play book handles the downloading of necessary packages and applies firewall opening on the server.

- name: Install necessary packages
  yum: name={{item}} state=installed
  with_items:
    - git
    - curl
    - wget
    - yum-utils
    - python-pip

- name: Install docker
  pip: name={{item}}
  with_items:
    - docker
    - docker-py

- name: Start and Enable the docker service
  service: name=docker state=started enabled=yes

# TODO: Don't do this.

- name: test to see if selinux is running and shut it off.
  command: getenforce
  register: sestatus
  changed_when: false

# TODO: Seriously, don't do that.

# Open up ports for all those dope applications.

- name: Open up plex port
  firewalld: port={{ plex_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sab port
  firewalld: port={{ sab_port1 }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sab port
  firewalld: port={{ sab_port2 }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for couch potato port
  firewalld: port={{ radarr_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sonarr port
  firewalld: port={{ sonarr_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for hydra port
  firewalld: port={{ hydra_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for ombi port
  firewalld: port={{ ombi_port }}/tcp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for organ port
  firewalld: port={{ organ_port }}/tcp permanent=true state=enabled immediate=yes

- name: Open up plex port
  firewalld: port={{ plex_port }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sab port
  firewalld: port={{ sab_port1 }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sab port
  firewalld: port={{ sab_port2 }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for couch potato port
  firewalld: port={{ radarr_port }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for sonarr port
  firewalld: port={{ sonarr_port }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for hydra port
  firewalld: port={{ hydra_port }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for ombi port
  firewalld: port={{ ombi_port }}/udp permanent=true state=enabled immediate=yes

- name: insert firewalld rule for organ port
  firewalld: port={{ organ_port }}/udp permanent=true state=enabled immediate=yes
