- name: setup and start the Ombi container
  docker_container:
    image: "linuxserver/ombi:latest"
    name: "ombi"
    env:
      PUID: '{{ user_id }}'
      PGID: '{{ group_id }}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '{{ ombi_directory }}:/config '
    ports: "{{ ombi_port }}:{{ ombi_port }}"
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "ombi"
