# Setup Plex Container
- name: plex container
  docker:
    name: plex
    image: linuxserver/plex
    state: reloaded
    pull: always
    net : host
    volumes:
    - "{{ host_plex_config_path }}:/config"
    - "{{ host_media_tv_path }}:/data/tvshows"
    - "{{ host_media_movies_path }}:/data/movies"
    - "{{ host_media_anime_path }}:/data/anime"
    - "{{ plex_transcode_path }}:/transcode"
    ports:
    - "32400:32400"
    env:
      TZ: {{ TZ_TimeZone }}
      PUID: {{ plex_user_id }}
      GUID: {{ plex_group_id }}
      VERSION: latest
