# Setup Plex Container
- name: plex container
  docker_container:
    name: "plex"
    image: "linuxserver/plex"
    state: "started"
    restart_policy: "always" 
    volumes:
    - "{{ host_plex_config_path }}:/config"
    - "{{ host_media_tv_path }}:/data/tvshows"
    - "{{ host_media_movies_path }}:/data/movies"
    - "{{ host_media_anime_path }}:/data/anime"
    - "{{ plex_transcode_path }}:/transcode"
    ports:
    - '32400:32400'
    - '33400:33400'
    - '32469:32469'
    - '5353:5353'
    - '1900:1900'
    log_driver: 'syslog'
    log_opt:
      tag: "plex"
    env:
      TZ: "{{ TZ_TimeZone }}"
      PUID: "{{ plex_user_id }}"
      GUID: "{{ plex_group_id }}"
      VERSION: "latest"
